apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: geoportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/<twoj_user>/geoportal-backend:latest
          env:
            - name: DATABASE_URL
              value: postgresql://geo:geo@postgres.geoportal.svc.cluster.local:5432/geo
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: geoportal
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
