apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: geoportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/<twoj_user>/geoportal-frontend:latest
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://backend.geoportal.svc.cluster.local:8000
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: geoportal
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
